using System.Web.Http;
using Owin;
using Microsoft.Practices.Unity;
using System.Web.Http.Cors;
using System.Net.Http.Formatting;
using System.Web.Http.Dependencies;
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Serialization;
using Swashbuckle.Application;

namespace ContosoEvents.WebApi
{
    public static class Startup
    {
        // This code configures Web API. The Startup class is specified as a type
        // parameter in the WebApp.Start method.
        public static void ConfigureApp(IAppBuilder appBuilder)
        {
            // Configure Web API for self-host. 
            HttpConfiguration configuration = new HttpConfiguration();

            // Unity iOC container registration
            var container = new UnityContainer();
            configuration.DependencyResolver = new UnityResolver(container);

            // Enable CORS (requires a NuGet package: Install-Package Microsoft.AspNet.WebApi.Cors)
            var cors = new EnableCorsAttribute("*", "*", "*");
            configuration.EnableCors(cors);

            // Bootstrap Web API
            // Web API Attribute Routing
            configuration.MapHttpAttributeRoutes();

            // Remove all formatters and just leave the JSON formatter
            // No negitiation...always return JSON
            configuration.Formatters.Clear();
            configuration.Formatters.Add(new JsonMediaTypeFormatter());

            // Camelize JSON
            var jsonFormatter = configuration.Formatters.OfType<JsonMediaTypeFormatter>().First();
            jsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();

            // Because we are running in Owin, we can't use the SwaggerConfig.cs that is auto-generated by the package. 
            // To see the swagger JSON file, http://localhost:8082/swagger/docs/v1
            configuration.EnableSwagger(c =>
            {
                c.SingleApiVersion("v1", "ContosoEvents.WebApi");
                //c.IncludeXmlComments(GetXmlCommentsPath());
                //c.ResolveConflictingActions(x => x.First());
            }).EnableSwaggerUi();

            // Let Web API work
            appBuilder.UseWebApi(configuration);
        }
    }


    public class UnityResolver : IDependencyResolver
    {
        protected IUnityContainer container;

        public UnityResolver(IUnityContainer container)
        {
            if (container == null)
            {
                throw new ArgumentNullException("container");
            }
            this.container = container;
        }

        public object GetService(Type serviceType)
        {
            try
            {
                return container.Resolve(serviceType);
            }
            catch (ResolutionFailedException)
            {
                return null;
            }
        }

        public IEnumerable<object> GetServices(Type serviceType)
        {
            try
            {
                return container.ResolveAll(serviceType);
            }
            catch (ResolutionFailedException)
            {
                return new List<object>();
            }
        }

        public IDependencyScope BeginScope()
        {
            var child = container.CreateChildContainer();
            return new UnityResolver(child);
        }

        public void Dispose()
        {
            container.Dispose();
        }
    }
}
